steps:
  - name: node:10.9.0
    entrypoint: yarn
    args: ['install']
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-d', '-r', 'build/', 'gs://vobees.vobi.io']
